### ISSUE TITLE
Cannot Build on iMac G3

### ISSUE THREAD

**Issue by ScttB** [dobyrch/termboy#6]
```
root@Apple-i3:/home/scottbeebiwan/git/termboy# make
g++ -x c++ -std=gnu++11  -I. -O3 -fomit-frame-pointer -march=native   -c target-ethos/ethos.cpp -o obj/ui-ethos.o
g++: error: unrecognized command line option ‘-march=native’
Makefile:64: recipe for target 'obj/ui-ethos.o' failed
make: *** [obj/ui-ethos.o] Error 1
```

Help? I can't get a UI to work so this is really all the emulation I can do.

**Comment by dobyrch** [comment]
I'm afraid you're out of luck—this relies on a few Linux-specific features and will likely never support Mac OS since I don't own any apple hardware to test on.  Sorry!

**Comment by ScttB** [comment]
It's not on Mac OS! I have a iMac G3 running Linux Mint!

**Comment by ScttB** [comment]
Also: If it was running Mac OS, Maybe I would have a fucking UI.
